name: Varredura Automática de Leilões

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  atualizar_lotes:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar API do Google para Varredura
        run: |
          curl -L -X POST "https://script.google.com/macros/s/AKfycbw3h4Xhe143SU2YymykGHxYnBXmOgcblnSnaCI4I-RmwSBVFKLCWuY438fqKSsoN826AA/exec" \
          -H "Content-Type: application/json" \
          -d '{"action": "varrer_todos_sites"}'
